version: "3.8"
services:
  es-master:
    image: elasticsearch:8.11.1
    container_name: es-master
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es-master
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-master,es-node1,es-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ=Asia/Shanghai
      # 节点角色
      - node.roles=master,data,ingest
    volumes:
      - ./es_master/data:/usr/share/elasticsearch/data
      - ./es_master/logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-network

  es-node1:
    image: elasticsearch:8.11.1
    container_name: es-node1
    restart: always
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - node.name=es-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-master,es-node2
      - cluster.initial_master_nodes=es-master,es-node1,es-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ=Asia/Shanghai
      # 节点角色
      - node.roles=master,data,ingest
    volumes:
      - ./es_node1/data:/usr/share/elasticsearch/data
      - ./es_node1/logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-network

  es-node2:
    image: elasticsearch:8.11.1
    container_name: es-node2
    restart: always
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-master,es-node1
      - cluster.initial_master_nodes=es-master,es-node1,es-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ=Asia/Shanghai
      # 节点角色
      - node.roles=master,data,ingest
    volumes:
      - ./es_node2/data:/usr/share/elasticsearch/data
      - ./es_node2/logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-network

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es-master:9200
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
      - xpack.encryptedSavedObjects.encryptionKey=fhjskloppd678ehkdfdlliverpoolfcr
    depends_on:
      - es-master
      - es-node1
      - es-node2
    volumes:
      - ./kibana_data:/usr/share/kibana/data
    networks:
      - es-network

networks:
  es-network:
    driver: bridge