version: "3.8"
services:
  sentinel1:
    image: redis:7.0.5
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  sentinel2:
    image: redis:7.0.5
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    volumes: 
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  sentinel3:
    image: redis:7.0.5
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    volumes: 
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

networks:
  default:
    external:
      name: redis_default