version: "3.8"
services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"
    restart: always
