version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # 单节点模式
      - discovery.type=single-node
      # 禁用安全认证（开发环境）
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # JVM内存设置
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 时区设置
      - TZ=Asia/Shanghai
      # 集群名称
      - cluster.name=docker-cluster
      # 节点名称
      - node.name=es-node1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch_logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Shanghai
      # 禁用安全认证
      - xpack.security.enabled=false
      - xpack.encryptedSavedObjects.encryptionKey=fhjskloppd678ehkdfdlliverpoolfcr
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./kibana_data:/usr/share/kibana/data

networks:
  default:
    name: elasticsearch