version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.1.2
    container_name: nacos-standalone
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
