version: "3.8"
services:
  redis-master:
    image: redis:7.0.5
    container_name: redis-master
    ports:
      - 6379:6379
    volumes: 
      - ./docker-volume/redis-master/:/data
    command: --requirepass root  --masterauth root
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    restart: always

  redis-slave1:
    image: redis:7.0.5
    container_name: redis-slave1
    ports:
      - 6380:6379
    volumes: 
      - ./docker-volume/redis-slave1/:/data
    command: redis-server --slaveof redis-master 6379 --requirepass root  --masterauth root
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on: 
      - redis-master
    restart: always

  redis-slave2:
    image: redis:7.0.5
    container_name: redis-slave2
    ports:
      - 6381:6379
    volumes: 
      - ./docker-volume/redis-slave2/:/data
    command: redis-server --slaveof redis-master 6379 --requirepass root  --masterauth root
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - redis-master
      - redis-slave1
    restart: always