version: "3.8"
services:
  redis:
    image: redis:7.0.5
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - ./data:/data
    command: redis-server --requirepass root
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    restart: always